<a href="https://colab.research.google.com/github/SUDHANSHU4497/practice/blob/main/tutorialspoint_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
from sklearn.preprocessing import Normalizer 
from numpy import set_printoptions

In [2]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [7]:
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 
'class'] 

df=pd.read_csv('/content/drive/MyDrive/dataset/pima-indians-diabetes.csv',names=names)

In [8]:
df

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [32]:

set_printoptions(precision=2)
Data_normalizer = Normalizer(norm='l1').fit(df) 
Data_normalized = Data_normalizer.transform(df) 

In [33]:

Data_normalized[:3]


array([[0.02, 0.43, 0.21, 0.1 , 0.  , 0.1 , 0.  , 0.14, 0.  ],
       [0.  , 0.36, 0.28, 0.12, 0.  , 0.11, 0.  , 0.13, 0.  ],
       [0.03, 0.59, 0.21, 0.  , 0.  , 0.07, 0.  , 0.1 , 0.  ]])

In [34]:
set_printoptions(precision=2)
Data_normalizer = Normalizer(norm='l2').fit(df) 
Data_normalized = Data_normalizer.transform(df) 

In [35]:
Data_normalized[:3]


array([[0.03, 0.83, 0.4 , 0.2 , 0.  , 0.19, 0.  , 0.28, 0.01],
       [0.01, 0.72, 0.56, 0.24, 0.  , 0.22, 0.  , 0.26, 0.  ],
       [0.04, 0.92, 0.32, 0.  , 0.  , 0.12, 0.  , 0.16, 0.01]])

In [36]:
# binarization
from sklearn.preprocessing import Binarizer

In [37]:
binarizer=Binarizer(threshold=0.5).fit(df)
data_binarized=binarizer.transform(df)

In [38]:
data_binarized[:3]

array([[1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 0., 0., 1., 1., 1., 1.]])

In [39]:
# standardization
from sklearn.preprocessing import StandardScaler

In [40]:
data_scalar=StandardScaler().fit(df)
data_rescaled=data_scalar.transform(df)

In [42]:
data_rescaled[:5]

array([[ 0.64,  0.85,  0.15,  0.91, -0.69,  0.2 ,  0.47,  1.43,  1.37],
       [-0.84, -1.12, -0.16,  0.53, -0.69, -0.68, -0.37, -0.19, -0.73],
       [ 1.23,  1.94, -0.26, -1.29, -0.69, -1.1 ,  0.6 , -0.11,  1.37],
       [-0.84, -1.  , -0.16,  0.15,  0.12, -0.49, -0.92, -1.04, -0.73],
       [-1.14,  0.5 , -1.5 ,  0.91,  0.77,  1.41,  5.48, -0.02,  1.37]])