<a href="https://colab.research.google.com/github/SUDHANSHU4497/practice/blob/main/Vectors%2C_Matrices%2C_and_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Load library
import numpy as np
# Create a vector as a row
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

In [4]:
vector_row

array([1, 2, 3])

In [5]:
vector_column

array([[1],
       [2],
       [3]])

In [2]:
# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [3]:
matrix 

array([[1, 2],
       [1, 2],
       [1, 2]])

In [8]:
from scipy import sparse

In [10]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

 
# View larger sparse matrix
print(matrix_large_sparse)
 

  (1, 1)	1
  (2, 0)	3


In [19]:
# Create matrix
matrix = np.array([[1, 5, 3],
                   [0, 5, 6],
                   [1, 5, 3]])

In [20]:
np.max(matrix, axis=0)

array([1, 5, 6])

In [21]:
np.max(matrix, axis=1)

array([5, 6, 5])

In [22]:
np.mean(matrix)

3.2222222222222223

In [23]:
np.var(matrix)

4.172839506172839

In [24]:
np.std(matrix)

2.042752923427804

In [26]:
# Find the mean value in each column
np.mean(matrix, axis=0)


array([0.66666667, 5.        , 4.        ])

In [27]:
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [29]:
# Transpose matrix
matrix.T


array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [30]:
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [31]:
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [32]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [33]:
# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
matrix.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [37]:
np.linalg.matrix_rank(matrix)

2

In [38]:
np.linalg.det(matrix)

0.0

In [39]:
matrix.diagonal()

array([1, 5, 9])

In [40]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)


array([4, 8])

In [42]:
# Return diagonal and sum elements
sum(matrix.diagonal())

15

In [43]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [44]:
eigenvalues

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

In [45]:
eigenvectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])