<a href="https://colab.research.google.com/github/SUDHANSHU4497/practice/blob/main/zeros_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
  
a =np.zeros(3, dtype = int) 
print("Matrix a : \n", a) 
  
b =np.zeros([3, 3], dtype = int) 
print("\nMatrix b : \n", b) 

Matrix a : 
 [0 0 0]

Matrix b : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
import pandas as pd  
      
# List1  
lst = [['patna', 612], ['lalganj', 6224], 
       ['hajipur', 6224], ['muzaffarpur', 621]] 
  
# creating df object with columns specified    
df = pd.DataFrame(lst, columns =['city', 'std code']) 
print(df )

          city  std code
0        patna       612
1      lalganj      6224
2      hajipur      6224
3  muzaffarpur       621


In [5]:
lst = [['anshu', 'kumar', 25], ['krish', 'kalra', 30], 
       ['nick', 'jones', 26], ['juli', 'khatri', 22]] 
      
df = pd.DataFrame(lst, columns =['FName', 'LName', 'Age'],
                                           dtype = float) 
print(df)

   FName   LName   Age
0  anshu   kumar  25.0
1  krish   kalra  30.0
2   nick   jones  26.0
3   juli  khatri  22.0


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)
