<a href="https://colab.research.google.com/github/SUDHANSHU4497/practice/blob/main/zeros_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
  
a =np.zeros(3, dtype = int) 
print("Matrix a : \n", a) 
  
b =np.zeros([3, 3], dtype = int) 
print("\nMatrix b : \n", b) 

Matrix a : 
 [0 0 0]

Matrix b : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
